[package]
name = "builder"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "0.19.0"
eyre = "0.6.12"
futures = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
tar = "0.4.44"
temp-dir = "0.1.16"
toml = "0.8.23"
