[package]
name = "sctf"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.3"
dotenvy = "0.15.7"
eyre = "0.6.12"
sqlx = { version = "0.8.5", features = ["postgres", "runtime-tokio"] }
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["rt-multi-thread"] }
tracing = "0.1.41"
