services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: nerine
      POSTGRES_PASSWORD: postgres
